        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 21 18:43:01 2022
        MODULE LSFILE__genmod
          INTERFACE 
            SUBROUTINE LSFILE(IOPTNS,INFORM)
              INTEGER(KIND=4) :: IOPTNS
              INTEGER(KIND=4) :: INFORM
            END SUBROUTINE LSFILE
          END INTERFACE 
        END MODULE LSFILE__genmod
