        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 21 18:43:03 2022
        MODULE OPLOOK__genmod
          INTERFACE 
            SUBROUTINE OPLOOK(NDICT,DICTRY,ALPHA,KEY,ENTRY)
              INTEGER(KIND=4) :: NDICT
              CHARACTER(*) :: DICTRY(NDICT)
              LOGICAL(KIND=4) :: ALPHA
              CHARACTER(*) :: KEY
              INTEGER(KIND=4) :: ENTRY
            END SUBROUTINE OPLOOK
          END INTERFACE 
        END MODULE OPLOOK__genmod
