        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 21 18:43:03 2022
        MODULE OPTOKN__genmod
          INTERFACE 
            SUBROUTINE OPTOKN(STRING,NUMBER,LIST)
              INTEGER(KIND=4) :: NUMBER
              CHARACTER(*) :: STRING
              CHARACTER(*) :: LIST(NUMBER)
            END SUBROUTINE OPTOKN
          END INTERFACE 
        END MODULE OPTOKN__genmod
