"""
Patch E1: insert new §4.5.11 'FreeForm Surfaces' immediately after
§4.5.10 'Interpolated Surfaces Using X-Y-Z Data'.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

from patch_base import apply, P_BODY, P_LIST, P_CODE, P_H4
from docx_helpers import (iter_paragraphs, get_style, get_text, wtag,
                          find_para_parent, make_para)


HEAD = "FreeForm Surfaces"

INTRO = (
    "FreeForm (SrfType = 14, Surface = FreeForm) is a single MACOS "
    "surface type combining up to four independent contributions:")

FORMULA = "    z(rho) = z_conic(rho) + z_Mon(rho) + z_FF(rho) + z_grid(rho)"

WHERE = "where:"

COMPONENTS = [
    "z_conic is the conic of revolution defined by KrElt, KcElt, and "
    "the optical axis psiElt through the vertex VptElt.",
    "z_Mon is a Cartesian-monomial sag in the local frame "
    "(pMon, xMon, yMon, zMon), normalized by aperture lMon, with "
    "coefficients MonCoef (or sparse MonZernCoef).  Active only when "
    "lMon > 0.",
    "z_FF is a free-form Zernike sag in an independent frame "
    "(pFF, xFF, yFF, zFF), normalized by lFF, with coefficients "
    "FFCoef (or sparse FFZernCoef).  Active only when lFF > 0.",
    "z_grid is an interpolated sag from a regularly-gridded data "
    "array, on an independent frame (pData, xData, yData, zData) with "
    "grid spacing GridSrfdx.  Active only when nGridMat > 0.",
]

COMBINE = (
    "Mon, FF, and grid contributions can be enabled in any "
    "combination; setting the corresponding sentinel to zero (or "
    "omitting it from the prescription) disables that term.")

WHY = (
    "Why three independent frames.  In segmented mirrors generated by "
    "SegMirMaker (§4.4.11), the FF coefficients describe the parent "
    "surface and the FF frame is parent-aligned (so all segments "
    "share the same FF Zernike set), while the Mon frame is "
    "per-segment (face-aligned) so each segment can carry its own "
    "figure error via MonZernCoef.  The grid frame is parent-aligned "
    "so the data array represents a global perturbation map.")

INDEPENDENCE = (
    "Independence is enforced in the surface evaluation.  The "
    "FreeFormSrf routine treats Mon, FF, and grid sags as "
    "displacements along their own z-axes (zMon, zFF, zData).  "
    "Earlier versions assumed all three shared a single z-axis, "
    "which produced incorrect intersections when, for example, the "
    "segment Mon frame was face-aligned with zMon = -psi while "
    "zFF = +psi (a 180-deg mismatch).")

EXAMPLE_HEAD = "Example.  Conic + Mon + FF + grid:"

EXAMPLE = (
    "    iElt=    1\n"
    "    EltName= primary\n"
    "    Element= Reflector\n"
    "    Surface= FreeForm\n"
    "      KrElt= -1.000D+02\n"
    "      KcElt= -1.0\n"
    "     psiElt=  0  0  1\n"
    "     VptElt=  0  0  0\n"
    "     RptElt=  0  0  0\n"
    "       lMon=  50.0\n"
    "       pMon=  0  0  0\n"
    "       xMon=  1  0  0\n"
    "       yMon=  0  1  0\n"
    "       zMon=  0  0  1\n"
    "    MonZernType= BornWolf\n"
    "    nMonZernCoef= 16\n"
    "    MonZernModes= 1 3 4 5 9 10 11 12 13 19 20 21 22 23 24 25\n"
    "    MonZernCoef= 1.197E+0  ...\n"
    "        lFF= 100.0\n"
    "        pFF=  0  0  0\n"
    "        xFF=  1  0  0\n"
    "        yFF=  0  1  0\n"
    "        zFF=  0  0  1\n"
    "    FFZernType= BornWolf\n"
    "    nFFZernCoef= 16\n"
    "    FFZernModes= ...\n"
    "    FFZernCoef=  ...\n"
    "    nGridMat= 256\n"
    "    GridFile= flat.txt\n"
    "    GridSrfdx= 31.25\n"
    "       pData= 0  0  0\n"
    "       xData= 1  0  0\n"
    "       yData= 0  1  0\n"
    "       zData= 0  0  1")


def transform(root):
    h = None
    for p in iter_paragraphs(root):
        if get_style(p) == "Heading4" and \
           "Interpolated Surfaces Using X-Y-Z" in get_text(p):
            h = p
            break
    if h is None:
        raise RuntimeError("Couldn't find §4.5.10 X-Y-Z Data heading")

    parent = find_para_parent(root, h)
    children = list(parent)
    idx = children.index(h) + 1
    # Walk forward to next H4 / H3.
    while idx < len(children):
        c = children[idx]
        if c.tag == wtag("p") and get_style(c) in ("Heading3", "Heading4"):
            break
        idx += 1

    new_paras = [
        make_para(P_H4, HEAD),
        make_para(P_BODY, INTRO),
        make_para(P_CODE, FORMULA),
        make_para(P_BODY, WHERE),
    ]
    new_paras.extend(make_para(P_LIST, c) for c in COMPONENTS)
    new_paras.append(make_para(P_BODY, COMBINE))
    new_paras.append(make_para(P_BODY, WHY))
    new_paras.append(make_para(P_BODY, INDEPENDENCE))
    new_paras.append(make_para(P_BODY, EXAMPLE_HEAD))
    new_paras.append(make_para(P_CODE, EXAMPLE))

    for offset, np in enumerate(new_paras):
        parent.insert(idx + offset, np)
    return {"new paragraphs": len(new_paras)}


if __name__ == "__main__":
    apply(__file__, transform)
