% clear all
% close all
% clc

macos_fname='peco48_v1.in';
write_fname='peco48_v11.in';
credits=strvcat('author: Luis Machen','Modified by: Luis Marchen','Description: adding TElt and GridSurfaces to peco48_v1.in prescription ');

%--------------------------------------------------------------------------
% Using the MACOS comman "ACO" compute the local coordinates of each
% element. The code below will required the file generated by this command
% in order to run. The code below will create the TElt parameter for each
% element of the optical system in macos_fname.
%--------------------------------------------------------------------------
[OpticalData]=MakeTEltRx(macos_fname,write_fname,credits);


%--------------------------------------------------------------------------
% Adds gridded surfaces to macos_fname
%--------------------------------------------------------------------------
gridElt=[1:21];
[ElementData]=makeGridSrf(OpticalData,gridElt);

%--------------------------------------------------------------------------
% Writes new MACOS optical prescription after changes made to TElt and
% Gridded surfaces.
%--------------------------------------------------------------------------
WriteRxFile(write_fname,ElementData,credits)











