#!/usr/bin/env python3
"""Generate macos_f90/glass_builtin.f90 from macos_f90/macos_glass_list.txt.

Bakes the full glass catalog (Sellmeier names + 6 coefficients per
glass) into the macos/smacos binaries (PLAN section 0: no separate
runtime glass-table file needed).  A macos_glass_list.txt found at
runtime still OVERRIDES the built-in catalog (unchanged precedence).

Usage:  python3 tools/gen_glass_builtin.py   (from the repo root)
Then rebuild.  Commit both the .txt and the regenerated .f90.
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "macos_f90" / "macos_glass_list.txt"
dst = root / "macos_f90" / "glass_builtin.f90"

names, rows = [], []
for line in src.read_text().splitlines():
    parts = line.split()
    if len(parts) != 7:
        if parts:
            raise SystemExit(f"bad glass line ({len(parts)} fields): {line}")
        continue
    names.append(parts[0])
    rows.append([float(x.replace("D", "E").replace("d", "e"))
                 for x in parts[1:]])

n = len(names)
w = max(len(s) for s in names)
lines = []
a = lines.append
a("! Generated by tools/gen_glass_builtin.py from macos_glass_list.txt")
a("! DO NOT EDIT BY HAND -- edit the txt and regenerate, then rebuild.")
a("!")
a("! Fills GlassName(2:)/GlassTable(:,2:) with the built-in catalog")
a("! (caller owns index 1 = Air).  Returns the number of glasses")
a("! loaded.  Used as the fallback when no macos_glass_list.txt is")
a("! found at runtime -- a found file still overrides (PLAN sec. 0).")
a("")
a("      SUBROUTINE LoadBuiltinGlass(GlassName, GlassTable, mG, nLoaded)")
a("        IMPLICIT NONE")
a("        INTEGER,          INTENT(IN)  :: mG")
a("        INTEGER,          INTENT(OUT) :: nLoaded")
a("        CHARACTER(len=*), INTENT(INOUT) :: GlassName(mG)")
a("        REAL*8,           INTENT(INOUT) :: GlassTable(6, mG)")
a(f"        INTEGER, PARAMETER :: NB = {n}")
a(f"        CHARACTER(len={w}), PARAMETER :: nm(NB) = [ &")
for i in range(0, n, 6):
    chunk = ", ".join(f"'{s:<{w}}'" for s in names[i:i+6])
    tail = ", &" if i + 6 < n else " ]"
    a(f"     &    {chunk}{tail}")
a("        REAL*8, PARAMETER :: tb(6, NB) = RESHAPE( [ &")
flat = [f"{v:.8E}".replace("E", "D") for row in rows for v in row]
# 6 values per line = one glass per line, readable + diffable
for i in range(0, len(flat), 6):
    chunk = ", ".join(flat[i:i+6])
    tail = ", &" if i + 6 < len(flat) else " ], [6, NB] )"
    a(f"     &    {chunk}{tail}")
a("        INTEGER :: i")
a("")
a("        nLoaded = MIN(NB, mG - 1)")
a("        DO i = 1, nLoaded")
a("          GlassName(i+1)  = nm(i)")
a("          GlassTable(:, i+1) = tb(:, i)")
a("        END DO")
a("      END SUBROUTINE LoadBuiltinGlass")
a("")
dst.write_text("\n".join(lines))
print(f"wrote {dst}: {n} glasses, name width {w}")
